
##################
### WINDOWRULE ###
##################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule = match:workspace special:discord, border_size 0, center on 
windowrule = match:workspace special:spotify, border_size 0, center on
windowrule = match:workspace special:telegram, border_size 0, center on
windowrule = match:workspace special:magic, border_size 0, center on
windowrule = match:workspace special:vscode, border_size 0, center on

windowrule = match:class ^(discord)$, workspace special:discord silent
windowrule = match:class ^(spotify)$, workspace special:spotify silent
windowrule = match:class ^(telegram)$, workspace special:telegram silent
windowrule = match:class ^(code-oss)$, workspace special:vscode silent