
###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$browser = brave
$menu = killall -9 rofi || rofi -show drun -p "Apps" -theme ~/.config/rofi/config.rasi  -display-colums 3
