
##################
### WINDOWRULE ###
##################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule = match:workspace special:magic, border_size 0, center on
windowrule = match:workspace special:virt, border_size 0, center on


windowrule = match:class ^(vesktop)$, workspace special:magic silent
windowrule = match:class ^(.*[Ss]potify.*)$, workspace special:magic silent
windowrule = match:class ^(.*[Tt]elegram.*)$, workspace special:magic silent
windowrule = match:class ^(codium)$, workspace 1 silent
windowrule = match:class ^(virt.manager)$, workspace special:virt silent 


windowrule = opacity 0.8 , match:class brave-browser
windowrule = opacity 0.8 , match:class kitty 
windowrule = opacity 0.8 , match:class spotify
windowrule = opacity 0.8 , match:class codium 
windowrule = opacity 0.8 , match:class vesktop
windowrule = opacity 0.8 , match:class org.telegram.desktop

